### PR TITLE
Fix issue 147

### PR DESCRIPTION
**Pull request by tinydetoon**
Change OrbitalBaseRepository Update method to include Building levels updates in the query.

### CODE REVIEW

**Comment by Kern046** [comment]
Hi there !

I just saw your pull request, thanks for the work !

The building fields cannot be updated in this method. I removed it due to some heavy bugs (the subprocesses often committed changes to the dataset in the same time than other scripts, so the final building level wasn't right). Instead, a new method must be implemented, a dedicated method to the base change type. You can implement it in the repository and then call it in the changeBaseType script instead of the unit of work flush method !

Don't hesitate to contact me if you have further questions :)

**Comment by tinydetoon** [comment]
Hello Kern,

I have updated accordingly to your comments. 
Hope it is better now

**Comment by Kern046** [comment]
It's all good to me ! Thanks for your work :D !

**Comment by acknowledge** [comment]
@tinydetoon Can you just remove the useless spaces you added in some places (see [here](https://github.com/rtfmcorp/asylamba-game/pull/152/files)). And for your new method, please use the correct indentations (tabs instead of spaces).

A tiny commit and I'll merge ;)

**Comment by tinydetoon** [comment]
I have clean the code. It should be better now. I will pay more attention for the next commits ;-)

**Comment by acknowledge** [comment]
Thanks for cleaning the extra spaces. 

But still, can you indent you method `updateBuildingLevels` with **tabs** instead of **spaces**. So that all the code uses the same conventions ;)

**Comment by tinydetoon** [comment]
Should be good !

**Review by acknowledge — APPROVED** [review]
No, it's not !

I merge, then commit, and I'll explain it to you here right after.

**Comment by acknowledge** [comment]
Ok, here we are. Please analyze [this commit](https://github.com/rtfmcorp/asylamba-game/commit/e84e46f334f064d3e67de9aa39a1263c4ae83ad2). It contains what I asked you to do. You indented your code with 4 spaces, but have to indent with 1 tabulation. And the indentation should be correct.

Now here some advices for you next contributions:
- Never work on the `master` branch! Go to the `dev` branch to fix issues!
- A good practice is to create a new branch from `dev` before any commit, so that when you submit your PR, you can work on something else while we review it. It may take some hours.
- You can reference an issue by typing "Fix #147" --> the "#" allows you to do it!

Ok that's it. Thanks for your contribution. And I hope my advice will help you in the future.

**Comment by tinydetoon** [comment]
Thanks for your advices and sorry for the rework you had to do. It seems to be a configuration in my netbeans.

**Comment by acknowledge** [comment]
No problem ;)
Yes probably, on most editors (or IDEs), you can tune this kind of parameters.

**Pull request merged**
